service: strudel-backend

custom:
  serverless-offline:
    port: 3001
  table: strudel-${opt:stage}
  region: eu-west-1
  vbtcContractAddr: "0x8a55f373dC25B6d638Aa406757eE5Bb5fBb3B9A5"

package:
  exclude:
    - src/**/*.test.js

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs10.x
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
       - sdb:GetAttributes
       - sdb:PutAttributes
      Resource: 
        - Fn::Join:
          - ""
          - - "arn:aws:sdb:*:*:domain/"
            - Ref: strudelDb

responseMappings: &response_mappings
  headers:
    Content-Type: "'application/json'"
  statusCodes:
      200:
          pattern: ''
          headers:
            Access-Control-Allow-Origin: "'*'"
          template:
            application/json: ""
      204:
          pattern: ''
          headers:
            Access-Control-Allow-Origin: "'*'"
          template:
            application/json: ""
      400:
          pattern: 'Bad Request: .*'
          headers:
            Access-Control-Allow-Origin: "'*'"
          template:
            application/json: ""
      404:
          pattern: 'Not Found: .*'
          headers:
            Access-Control-Allow-Origin: "'*'"
          template:
            application/json: ""
      408:
          pattern: 'Not Found: .*'
          headers:
            Access-Control-Allow-Origin: "'*'"
          template:
            application/json: ""
      500:
          pattern: 'Error: .*'
          headers:
            Access-Control-Allow-Origin: "'*'"

functions:
  circleProxy:
    timeout: 3
    handler: src/strudel.handler
    name: strudel-${opt:stage}
    environment:
      ENV: ${opt:stage}
      PROVIDER_URL: ${env:PROVIDER_URL}
      BCD_URL: ${env:BCD_URL}
      VBTC_ADDR: ${env:VBTC_ADDR, self:custom.vbtcContractAddr}
      TABLE_NAME:
        Ref: strudelDb
    events:
      - http:
          method: any
          path: /account/{address+}
          integration: lambda
          cors: true
          response: *response_mappings

plugins:
  - serverless-offline

resources:
  Resources:
    strudelDb:
      Type: "AWS::SDB::Domain"
      Properties:
        DomainName : ${self:custom.table}
        Description: "SDB Domain to store metadata"